### ISSUE TITLE
Add Grafana Labs documentation

### ISSUE THREAD

**Issue by RichiH** [aws-otel/aws-otel.github.io#39]
** Grafana Cloud Agent **

The Grafana Cloud Agent is an all-in-one agent for collecting metrics, logs,
and traces, built on top of production-ready open source software. The
batteries-included nature removes the need to install more than one piece of
software by including common integrations for monitoring out of the box.
Through our native integrations with OpenTelemetry, Prometheus, and
OpenMetrics, we ensure full compatibility with the complete CNCF ecosystem
while adding extra functionality for scaling collection.

** Requirements **

Dependencies:

- OpenTelemetry-Collector
- Prometheus
- Cortex
- Loki

Runtime requirements:

- ETCD or Consul for scaling functionality

** Configuration **

Create a YAML configuration file with the following contents to configure the
Agent to collect metrics a Prometheus- or OpenMetrics-compatible endpoint:

```yaml
prometheus:
  # Configures where scraped metric data will be stored. Data read from this
  # directory will be forwarded using the configured remote_write settings.
  # this directory
  wal_directory: /tmp/agent
  configs:
    # An invidiual config here identifies a single Prometheus instance. Each
    # instance holds its own set of scrape jobs and remote_write settings. The
    # name specified here must be unique.
    - name: primary
      scrape_configs:
        # A job is responsible for discovering a set of targets to scrape.
        # static_configs specifies a static list of host:port pairs to use
        # as targets. Replace "host:port" below with the hostname and port
        # number of the OpenMetrics-compatible endpoint to collect metrics
        # from.
        - job_name: collect
          static_configs:
            - targets: ['host:port']
      # remote_write configures where to send metrics using the Prometheus
      # Remote Write format. If authentication is used, replace USERNAME and
      # password accordingly. Otherwise, omit the basic_auth block.
      remote_write:
        - url: REMOTE_WRITE_URL
          basic_auth:
            username: USERNAME
            password: PASSWORD
```

Integrations may be enabled to also collect metrics from common systems. Add the
following block to your configuration file:

```yaml
integrations:
  # Enable the "node_exporter" integration, which runs
  # https://github.com/prometheus/node_exporter in-process and scrapes metrics
  # from it.
  node_exporter:
    enabled: true
  # Configured identically to remote_write from the previous section. This
  # section must exist if integrations are used.
  prometheus_remote_write:
    - url: REMOTE_WRITE_URL
      basic_auth:
        username: USERNAME
        password: PASSWORD
```

Log support may be added by adding a `loki` block. Use the following code block
to collect all log files from `/var/log`:

```yaml
loki:
  positions:
    # Configures where to store byte offsets of recently read files.
    filename: /tmp/positions.yaml
  clients:
    # Configures the location to send logs using the Loki write API.
    # If authentication is not needed, omit the basic_auth block.
    - url: LOKI_URL
      basic_auth:
        username: USERNAME
        password: PASSWORD
  scrape_configs:
  # Configures a scrape job to find log files to collect from. Targets
  # must be set to localhost.
  #
  # __path__ may be set to any glob-patterned filepath where log files are
  # stored.
  - job_name: varlogs
    static_configs:
      - targets:
        - localhost
        labels:
          __path__: /var/log/*log
```

Support for collecting traces may be added with a `tempo` block. Use the
following code block to collect spans and forward them to an OTLP-compatible
endpoint:

```yaml
tempo:
  receivers:
    # Configure jaeger support. grpc supports spans over port
    # 14250, thrift_binary over 6832, thrift_compact over 6831,
    # and thrift_http over 14268. Specific port numbers may be
    # customized within the config for the protocol.
    jaeger:
      protocols:
        grpc:
        thrift_binary:
        thrift_compact:
        thrift_http:
    # Configure opencensus support. Spans can be sent over port 55678
    # by default.
    opencensus:
    # Configure otlp support. Spans can be sent to port 55680 by
    # default.
    otlp:
      protocols:
        grpc:
        http:
    # Configure zipkin support. Spans can be sent to port 9411 by
    # default.
    zipkin:

  # Configures where to send collected spans and traces. Outgoing spans are sent
  # in the OTLP format. Replace OTLP_ENDPOINT with the host:port of the target
  # OTLP-compatible host. If the OTLP endpoint uses authentication, configure
  # USERNAME and PASSWORD accordingly. Otherwise, omit the basic_auth section.
  push_config:
    endpoint: OTLP_ENDPOINT
    basic_auth:
      username: USERNAME
      password: PASSWORD
```

A full configuration reference is located in the [Grafana Cloud Agent code
repository](https://github.com/grafana/agent/blob/master/docs/configuration-reference.md).

** Sample Application **

Wide adoption from international banks to Fortune 500 companies.
