### ISSUE TITLE
missing port in address and opentelemetry-operator-webhook-service errors

### ISSUE THREAD

**Issue by lifeofmoo** [aws-otel/aws-otel.github.io#682]
Hello,

I've been playing around with the Adot implementation for the past several months and everything was working fine. I've started to revisit this as i'm looking to do do some eventbridge and PagerDuty in 2024.

I've had it deployed across all my eks clusters for while but now seeing this error:

eks: v1.25 
Adot Operator = v0.82.0-eksbuild.1

The Operator installs fine into the opentelemetry-operator-system NS:

```NAME                                          READY   STATUS    RESTARTS   AGE
pod/opentelemetry-operator-75b5b48d57-4xnlr   2/2     Running   0          25m

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
service/opentelemetry-operator           ClusterIP   10.100.55.136   <none>        8443/TCP,8080/TCP   25m
service/opentelemetry-operator-webhook   ClusterIP   10.100.145.90   <none>        443/TCP             25m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/opentelemetry-operator   1/1     1            1           25m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/opentelemetry-operator-75b5b48d57   1         1         1       25m
```
I've then installed the following collector into a NS called: opentelemetry, which hasn't changed in the several months and was working fine.

```
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: collector-xray
spec:
  mode: deployment
  resources:
    requests:
      cpu: "1"
    limits:
      cpu: "1"
  serviceAccount: adot-collector
  env:
    - name: CLUSTER_NAME
      value: eksdev
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch/traces:
        timeout: 1s
        send_batch_size: 50
      resourcedetection/eks:
        detectors: [env, eks]
        timeout: 2s
        override: false

    exporters:
      awsxray:
        region: eu-west-1
        index_all_attributes: true

      logging:
        loglevel: debug
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [resourcedetection/eks, batch/traces]
          exporters: [awsxray,logging]

      telemetry:
        logs:
          level: debug

```

I'm trying to deploy the following:

https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/config-auto-instrumentation#configuring-the-auto-instrumentation

I'm see this seeing this error in the operator logs:

> {"level":"info","ts":"2023-12-18T15:28:07Z","logger":"controllers.OpenTelemetryCollector","msg":"couldn't determine metrics port from configuration, using 8888 default value","opentelemetrycollector":{"name":"collector-xray","namespace":"opentelemetry"},"error":"missing port in address"}
{"level":"error","ts":"2023-12-18T15:28:07Z","logger":"controllers.OpenTelemetryCollector","msg":"Cannot create liveness probe.","opentelemetrycollector":{"name":"collector-xray","namespace":"opentelemetry"},"error":"service property in the configuration doesn't contain extensions","stacktrace":"github.com/open-telemetry/opentelemetry-operator/internal/manifests/collector.Container\n\t/workspace/internal/manifests/collector/container.go:127\ngithub.com/open-telemetry/opentelemetry-operator/internal/manifests/collector.Deployment\n\t/workspace/internal/manifests/collector/deployment.go:56\ngithub.com/open-telemetry/opentelemetry-operator/pkg/collector/reconcile.Deployments\n\t/workspace/pkg/collector/reconcile/deployment.go:40\ngithub.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).RunTasks\n\t/workspace/controllers/opentelemetrycollector_controller.go:237\ngithub.com/open-telemetry/opentelemetry-operator/controllers.(*OpenTelemetryCollectorReconciler).Reconcile\n\t/workspace/controllers/opentelemetrycollector_controller.go:225\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226"}

But also see this in Argo for the Sample java app i've deployed.

> Sync operation to 7277bf3b0ec3e1545fe05c4474645c771126661e failed: one or more objects failed to apply, reason: Internal error occurred: failed calling webhook "vinstrumentationcreateupdate.kb.io": failed to call webhook: Post "https://opentelemetry-operator-webhook-service.opentelemetry-operator-system.svc:443/validate-opentelemetry-io-v1alpha1-instrumentation?timeout=10s": service "opentelemetry-operator-webhook-service" not found

I see this within Argo for the app i've added the instrumentation to.
> 
Resource not found in cluster: [opentelemetry.io/v1alpha1/Instrumentation:my-instrumentation](http://opentelemetry.io/v1alpha1/Instrumentation:my-instrumentation) (edited)

Note: I was also half way through migrating to 0.88 but gave up on this due to incomplete info on the migration guide and not introducing extra variables (i.e creating the new IAM role and setting advanced add on config etc).

**Comment by lifeofmoo** [comment]
Hi @bryan-aguilar,

Thanks for the reply:

1) I believe the collector does deploy successfully - and I am able to see traces in x-ray for another app that had the aws-otel-java bundled in the dockerfile.

```
k describe deployments.apps -n opentelemetry
Name:                   collector-xray-collector
Namespace:              opentelemetry
CreationTimestamp:      Mon, 18 Dec 2023 13:35:07 +0000
Labels:                 app.kubernetes.io/component=opentelemetry-collector
                        app.kubernetes.io/instance=opentelemetry.collector-xray
                        app.kubernetes.io/managed-by=opentelemetry-operator
                        app.kubernetes.io/name=collector-xray-collector
                        app.kubernetes.io/part-of=opentelemetry
                        app.kubernetes.io/version=latest
Annotations:            deployment.kubernetes.io/revision: 1
                        opentelemetry-operator-config/sha256: 4861247396c8db39b085205e5d76c4ef07cde0112d12128b81021bc7f567bc21
                        prometheus.io/path: /metrics
                        prometheus.io/port: 8888
                        prometheus.io/scrape: true
Selector:               app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=opentelemetry.collector-xray,app.kubernetes.io/managed-by=opentelemetry-operator,app.kubernetes.io/part-of=opentelemetry
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/component=opentelemetry-collector
                    app.kubernetes.io/instance=opentelemetry.collector-xray
                    app.kubernetes.io/managed-by=opentelemetry-operator
                    app.kubernetes.io/name=collector-xray-collector
                    app.kubernetes.io/part-of=opentelemetry
                    app.kubernetes.io/version=latest
  Annotations:      opentelemetry-operator-config/sha256: 4861247396c8db39b085205e5d76c4ef07cde0112d12128b81021bc7f567bc21
                    prometheus.io/path: /metrics
                    prometheus.io/port: 8888
                    prometheus.io/scrape: true
  Service Account:  adot-collector
  Containers:
   otc-container:
``
    Image:       public.ecr.aws/aws-observability/aws-otel-collector:v0.32.0
    Ports:       8888/TCP, 4317/TCP, 4318/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Args:
      --config=/conf/collector.yaml
    Limits:
      cpu:  1
    Requests:
      cpu:  1
    Environment:
      CLUSTER_NAME:  eksdev
      POD_NAME:       (v1:metadata.name)
    Mounts:
      /conf from otc-internal (rw)
  Volumes:
   otc-internal:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      collector-xray-collector
    Optional:  false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   collector-xray-collector-75899f9dcc (1/1 replicas created)
Events:          <none>
```

2) The instrumentation manifest is based on the [docs](https://aws-otel.github.io/docs/getting-started/adot-eks-add-on/config-auto-instrumentation#configuring-the-auto-instrumentation)
 
Here's the snippets:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  # namespace: nextjs
  name: inws-java
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: inws-java
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inws-java
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
```
```
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
spec:
  exporter:
    endpoint: http://collector-xray-collector.opentelemetry:4317
  java:
    image: public.ecr.aws/aws-observability/adot-autoinstrumentation-java:v1.28.0
```

3) 

```
kubectl get customresourcedefinitions
NAME                                         CREATED AT
applications.argoproj.io                     2021-04-26T14:13:08Z
applicationsets.argoproj.io                  2022-04-05T08:09:31Z
appprojects.argoproj.io                      2021-04-26T14:13:08Z
awsnodetemplates.karpenter.k8s.aws           2023-08-21T11:09:37Z
certificaterequests.cert-manager.io          2022-02-01T16:25:46Z
certificates.cert-manager.io                 2022-02-01T16:25:46Z
challenges.acme.cert-manager.io              2022-02-01T16:25:46Z
clusterissuers.cert-manager.io               2022-02-01T16:25:46Z
clusterworkflowtemplates.argoproj.io         2021-06-08T15:41:39Z
cninodes.vpcresources.k8s.aws                2023-08-14T21:25:31Z
cronworkflows.argoproj.io                    2021-06-08T15:41:39Z
eniconfigs.crd.k8s.amazonaws.com             2021-04-26T10:27:29Z
extensions.dashboard.tekton.dev              2021-06-02T12:54:15Z
ingressclassparams.elbv2.k8s.aws             2022-02-16T11:17:43Z
instrumentations.opentelemetry.io            2023-12-18T11:34:50Z
issuers.cert-manager.io                      2022-02-01T16:25:46Z
machines.karpenter.sh                        2023-08-21T11:09:37Z
opentelemetrycollectors.opentelemetry.io     2023-12-18T11:34:49Z
orders.acme.cert-manager.io                  2022-02-01T16:25:46Z
policyendpoints.networking.k8s.aws           2023-10-18T08:34:37Z
provisioners.karpenter.sh                    2023-08-21T11:09:37Z
sealedsecrets.bitnami.com                    2021-04-26T14:50:59Z
securitygrouppolicies.vpcresources.k8s.aws   2021-04-26T10:27:32Z
targetgroupbindings.elbv2.k8s.aws            2021-04-26T14:06:11Z
workfloweventbindings.argoproj.io            2021-06-08T15:41:39Z
workflows.argoproj.io                        2021-06-08T15:41:39Z
workflowtemplates.argoproj.io                2021-06-08T15:41:39Z
```

Interesting I haven't touched the live cluster yet 

But the output of 4) has got two extra services...

```
kubectl get services -n opentelemetry-operator-system
NAME                                                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
opentelemetry-operator                                      ClusterIP   10.100.77.72     <none>        8443/TCP,8080/TCP   118d
**opentelemetry-operator-controller-manager-metrics-service   ClusterIP   10.100.57.137    <none>        8443/TCP,8080/TCP   140d**
opentelemetry-operator-webhook                              ClusterIP   10.100.122.149   <none>        443/TCP             118d
**opentelemetry-operator-webhook-service                      ClusterIP   10.100.84.129    <none>        443/TCP             140d**
```

If it's any help here are some recent logs from Cert Manager cert-manager-cainjector pod

```
I1218 16:31:13.762847       1 reconciler.go:142] "cert-manager: Updated object" kind="mutatingwebhookconfiguration" kind="mutatingwebhookconfiguration" name="cert-manager-webhook"I1218 16:31:13.763122       1 reconciler.go:142] "cert-manager: Updated object" kind="validatingwebhookconfiguration" kind="validatingwebhookconfiguration" name="opentelemetry-operator-validation"I1218 16:31:13.768505       1 reconciler.go:142] "cert-manager: Updated object" kind="validatingwebhookconfiguration" kind="validatingwebhookconfiguration" name="aws-load-balancer-webhook"I1218 16:31:13.768834       1 reconciler.go:142] "cert-manager: Updated object" kind="mutatingwebhookconfiguration" kind="mutatingwebhookconfiguration" name="opentelemetry-operator-mutation"I1218 16:31:13.773718       1 reconciler.go:142] "cert-manager: Updated object" kind="validatingwebhookconfiguration" kind="validatingwebhookconfiguration" name="cert-manager-webhook"I1218 16:31:13.774599       1 reconciler.go:142] "cert-manager: Updated object" kind="mutatingwebhookconfiguration" kind="mutatingwebhookconfiguration" name="aws-load-balancer-webhook"I1218 16:31:13.778965       1 reconciler.go:142] "cert-manager: Updated object" kind="validatingwebhookconfiguration" kind="validatingwebhookconfiguration" name="opentelemetry-operator-validating-webhook-configuration"
```
